name: Sync Upstream

on:
  schedule:
    - cron: '0 3 * * *' # 每天 UTC+0 时间凌晨 3 点运行（北京时间 11 点）
  workflow_dispatch:     # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your fork
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Git
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your GitHub Name"

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/217heidai/adblockfilters.git
          git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories -m "Sync with upstream"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
